version: '3.4'

services:
  nestjs-challenge:
    image: mysql
    container_name: nestjs-challenge
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    hostname: kevin
    networks:
      - default
    ports:
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root